function [fitresult, gof] = PHLLnSolve(ppp,eq)
%CREATEFIT(Y,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Y
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Sep-2013 00:58:27


%% Fit: 'untitled fit 1'.
len=size(ppp,2);
x=linspace(1,len,len);
y=feval(eq,x);
Y=



[xData, yData] = prepareCurveData( Y, y );

% Set up fittype and options.
ft = fittype( 'a*log(b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [-1 100 1];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
